<b> But de l'exerice </b>

L'objectif est d'apprendre à utiliser l'API restcountries, qui permet d'obtenir des données sur tous les Pays du monde. <br>

1) Faites une lecture rapide de la documentation de l'API : https://restcountries.eu/ <br>
2) Via requests.get et .content, tester le bon fonctionnement de l'API en requetant https://restcountries.eu/rest/v2/all. Récupérez vous bien des données ? Quel est code réponse de l'API ? <br>
3) Enregistrer le contenu de l'API dans la variable data. reformater data au format json grace à json.loads <br>
4) Créer un tableau pandas appelé dataSet, à partir de data et la fonction json_normalize. Visualisez les données. <br>
5) il y a beaucoup trop de données...nous allons simplifier cela. Refaire de même process d'appel mais cette fois avec cette API : https://restcountries.eu/rest/v2/alpha?codes=FRA . Il ne doit maintenir y avoir qu'une seul ligne correspondant aux infos sur la France<br>
6) Mettre l'information 'code' dans les paramètre d'appel de l'API (params=..) puis le supprimer de l'URL. <br>
7) Nous allons construire une fonction permettant d'obtenir une information précise sur un pays. <br>
le comportement attendue est le suivant : la fonction infoPays('FRA','capital') devra retourner 'Paris' <br>
7-1) Déclarer la fonction infoPays qui prendra 2 paramètres : 'code', correspondant au code du pays et 'info' correspondant au contenu de la colonne à retourner (capital, monnaie...) <br>
7-2) placer dans la fonction l'appel à l'API réalisé à l'étape 6. la variable 'code' de l'api prendra la valeur du paramètre 'code' de la fonction infoPays <br>
7-3) Toujours dans la fonction créer ensuite la variable 'info' qui recupera la valeur de la colonne correspondant au paramètre 'info' de la fonction <br>
7-4) la fonction doit retourner la variable info en guise de réponse. <br>
8) quel est la capitale (capital) du bangladesh (BGD) ? <br>
9) quelle est la monnaie (currencies) de la Turquie(TUR) ?

In [8]:
import requests
import json
from pandas.io.json import json_normalize
import pandas

url_1='https://restcountries.eu/rest/v2/all'
data=requests.get(url_1)
data=json.loads(data.content)
dataSet=json_normalize(data)
dataSet

<ipython-input-8-db05bcb925b0>:9: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  dataSet=json_normalize(data)

,name,topLevelDomain,alpha2Code,alpha3Code,callingCodes,capital,altSpellings,region,subregion,population,...,translations.de,translations.es,translations.fr,translations.ja,translations.it,translations.br,translations.pt,translations.nl,translations.hr,translations.fa
0,Afghanistan,[.af],AF,AFG,[93],Kabul,"[AF, Afġānistān]",Asia,Southern Asia,27657145,...,Afghanistan,Afganistán,Afghanistan,アフガニスタン,Afghanistan,Afeganistão,Afeganistão,Afghanistan,Afganistan,افغانستان
1,Åland Islands,[.ax],AX,ALA,[358],Mariehamn,"[AX, Aaland, Aland, Ahvenanmaa]",Europe,Northern Europe,28875,...,Åland,Alandia,Åland,オーランド諸島,Isole Aland,Ilhas de Aland,Ilhas de Aland,Ålandeilanden,Ålandski otoci,جزایر الند
2,Albania,[.al],AL,ALB,[355],Tirana,"[AL, Shqipëri, Shqipëria, Shqipnia]",Europe,Southern Europe,2886026,...,Albanien,Albania,Albanie,アルバニア,Albania,Albânia,Albânia,Albanië,Albanija,آلبانی
3,Algeria,[.dz],DZ,DZA,[213],Algiers,"[DZ, Dzayer, Algérie]",Africa,Northern Africa,40400000,...,Algerien,Argelia,Algérie,アルジェリア,Algeria,Argélia,Argélia,Algerije,Alžir,الجزایر
4,American Samoa,[.as],AS,ASM,[1684],Pago Pago,"[AS, Amerika Sāmoa, Amelika Sāmoa, Sāmoa Amelika]",Oceania,Polynesia,57100,...,Amerikanisch-Samoa,Samoa Americana,Samoa américaines,アメリカ領サモア,Samoa Americane,Samoa Americana,Samoa Americana,Amerikaans Samoa,Američka Samoa,ساموآی آمریکا
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,Wallis and Futuna,[.wf],WF,WLF,[681],Mata-Utu,"[WF, Territory of the Wallis and Futuna Island...",Oceania,Polynesia,11750,...,Wallis und Futuna,Wallis y Futuna,Wallis-et-Futuna,ウォリス・フツナ,Wallis e Futuna,Wallis e Futuna,Wallis e Futuna,Wallis en Futuna,Wallis i Fortuna,والیس و فوتونا
246,Western Sahara,[.eh],EH,ESH,[212],El Aaiún,"[EH, Taneẓroft Tutrimt]",Africa,Northern Africa,510713,...,Westsahara,Sahara Occidental,Sahara Occidental,西サハラ,Sahara Occidentale,Saara Ocidental,Saara Ocidental,Westelijke Sahara,Zapadna Sahara,جمهوری دموکراتیک عربی صحرا
247,Yemen,[.ye],YE,YEM,[967],Sana'a,"[YE, Yemeni Republic, al-Jumhūriyyah al-Yamani...",Asia,Western Asia,27478000,...,Jemen,Yemen,Yémen,イエメン,Yemen,Iêmen,Iémen,Jemen,Jemen,یمن
248,Zambia,[.zm],ZM,ZMB,[260],Lusaka,"[ZM, Republic of Zambia]",Africa,Eastern Africa,15933883,...,Sambia,Zambia,Zambie,ザンビア,Zambia,Zâmbia,Zâmbia,Zambia,Zambija,زامبیا
249,Zimbabwe,[.zw],ZW,ZWE,[263],Harare,"[ZW, Republic of Zimbabwe]",Africa,Eastern Africa,14240168,...,Simbabwe,Zimbabue,Zimbabwe,ジンバブエ,Zimbabwe,Zimbabwe,Zimbabué,Zimbabwe,Zimbabve,زیمباوه

In [2]:
url_2='https://restcountries.eu/rest/v2/alpha?codes=FRA'
appel_API(url_2)

<ipython-input-1-44cb0c0537ed>:10: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  dataSet=json_normalize(data)

,name,topLevelDomain,alpha2Code,alpha3Code,callingCodes,capital,altSpellings,region,subregion,population,...,translations.de,translations.es,translations.fr,translations.ja,translations.it,translations.br,translations.pt,translations.nl,translations.hr,translations.fa
0,France,[.fr],FR,FRA,[33],Paris,"[FR, French Republic, République française]",Europe,Western Europe,66710000,...,Frankreich,Francia,France,フランス,Francia,França,França,Frankrijk,Francuska,فرانسه

In [3]:
url_3='https://restcountries.eu/rest/v2/alpha'
parametres={'codes':'FRA'}
data=requests.get(url_3, params=parametres)
data=json.loads(data.content)
dataSet=json_normalize(data)
dataSet

<ipython-input-3-58f557ef0855>:5: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  dataSet=json_normalize(data)

,name,topLevelDomain,alpha2Code,alpha3Code,callingCodes,capital,altSpellings,region,subregion,population,...,translations.de,translations.es,translations.fr,translations.ja,translations.it,translations.br,translations.pt,translations.nl,translations.hr,translations.fa
0,France,[.fr],FR,FRA,[33],Paris,"[FR, French Republic, République française]",Europe,Western Europe,66710000,...,Frankreich,Francia,France,フランス,Francia,França,França,Frankrijk,Francuska,فرانسه

In [13]:
url_3='https://restcountries.eu/rest/v2/alpha'

def infoPays(code, info):
    parametres={'codes':code
               }
    data=requests.get(url_3, params=parametres)
    data=json.loads(data.content)
    dataSet=json_normalize(data)
    info= dataSet[info][0]
    return info

In [14]:
infoPays('FRA','capital')

<ipython-input-13-31cae2b892a3>:8: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  dataSet=json_normalize(data)

'Paris'

In [16]:
infoPays('AFG','capital')

<ipython-input-13-31cae2b892a3>:8: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  dataSet=json_normalize(data)

'Kabul'

In [17]:
infoPays('FRA','currencies')

<ipython-input-13-31cae2b892a3>:8: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  dataSet=json_normalize(data)

[{'code': 'EUR', 'name': 'Euro', 'symbol': '€'}]